import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono } from "next/font/google"; // Restore original fonts
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { ConvexProviderWrapper } from "@/components/ConvexProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Please Please Please",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0", // Added for responsive mobile breakpoints
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${spaceMono.variable} antialiased`}
        >
          <ConvexProviderWrapper>{children}</ConvexProviderWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
